CREATE TABLE USER_ADDRESS (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    label       VARCHAR(30)  NOT NULL DEFAULT '',
    receiver_name VARCHAR(50) NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    zip_code    VARCHAR(10)  NOT NULL,
    address1    VARCHAR(200) NOT NULL,
    address2    VARCHAR(200) NOT NULL DEFAULT '',
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_address_user FOREIGN KEY (user_id) REFERENCES USER_ENTITY(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
