-- Add buy_price and rental_price columns to PRODUCT table
ALTER TABLE PRODUCT ADD COLUMN buy_price INT NOT NULL DEFAULT 0;
ALTER TABLE PRODUCT ADD COLUMN rental_price INT NOT NULL DEFAULT 0;

-- Extend image_URL column length from 50 to 512
ALTER TABLE PRODUCT_IMAGE MODIFY COLUMN image_URL VARCHAR(512) NOT NULL;

-- Fix PRODUCT_OPTION buy_price and rental_price from FLOAT to INT
ALTER TABLE PRODUCT_OPTION MODIFY COLUMN buy_price INT NOT NULL;
ALTER TABLE PRODUCT_OPTION MODIFY COLUMN rental_price INT NOT NULL;
